version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11
  pre_build:
    commands:
      - bundle install
  build:
    commands:
      - bundle exec jekyll b
artifacts:
  name: landy
  base-directory: _site
  files:
      - '**/*'