version: 0.1

phases:
  install:
    runtime-versions:
      java: corretto11
  pre_build:
    commands:
      - bundle install
  build:
    commands:
      - bundle exec jekyll b
artifacts:
  baseDirectory: _site
  files:
      - '**/*'